import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
//  import "./globals.css";

import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <nav>
          <h1>Navbar</h1>
          <ul>
            <li><Link href={'/'}>Inicio</Link></li>
            <li><Link href={'/nosotros'}>Nosotros</Link></li>
            <li><Link href={'/eventos'}>Eventos</Link></li>
            <li><Link href={'/oportunidades'}>Oportunidades</Link></li>
          </ul>
        </nav>

        { children }
      </body>
    </html>
  );
}
