import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";

import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <nav className="nav">
          <h1 className="font-bold text-lg">RIdeC</h1>
          <ul className="flex gap-4">
            <li><Link className="nav-link" href={'/'}>Inicio</Link></li>
            <li><Link className="nav-link" href={'/nosotros'}>Nosotros</Link></li>
            <li><Link className="nav-link" href={'/eventos'}>Eventos</Link></li>
            <li><Link className="nav-link" href={'/oportunidades'}>Oportunidades</Link></li>
          </ul>
        </nav>

        { children }
      </body>
    </html>
  );
}
